#services:
 # - type: web
   # name: ecom
   # env: python
  #  root: ecom
  #  buildCommand: bash ./install_requirements.sh
  #  startCommand: gunicorn ecom.wsgi:application


  services:
  - type: web
    name: ecom
    env: python
    buildCommand: bash ./install_requirements.sh
    startCommand: gunicorn ecom.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecom.settings
      - key: SECRET_KEY
        value: DJANGO_SECRET_KEY
      - key: DATABASE_URL
        value: DATABASE_URL1
